name        : SFML
version     : 2.3.2
release     : 1
source      :
    - http://www.sfml-dev.org/files/SFML-2.3.2-sources.zip : 03fe79943c48222037f1126a581b12c95a4dd53168881907964695c5ec3dc395
license     :
    - zlib
component   : multimedia.library
summary     : A simple, fast, cross-platform, and object-oriented multimedia API
description : |
    SFML provides a simple interface to the various components of your PC, to ease the development of games and multimedia applications. It is composed of five modules: system, window, graphics, audio and network.
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(openal)
    - pkgconfig(glew)
    - pkgconfig(flac)
    - pkgconfig(vorbis)
    - pkgconfig(vorbisenc)
    - pkgconfig(xcb-image)
    - pkgconfig(freetype2)
    - libjpeg-turbo-devel
setup      : |
    %cmake -DSFML_INSTALL_PKGCONFIG_FILES=1 -DSFML_BUILD_EXAMPLES=1
build      : |
    %make
install    : |
    %make_install
