name        : SFML
version     : 2.4.0
release     : 2
source      :
    - http://www.sfml-dev.org/files/SFML-2.4.0-sources.zip : 868a1a1e43a7ee40c1a90efcbcea061b6f0a6ed129075d9a8f19c8c69e644b0f
license     : zlib
component   : multimedia.library
summary     : A simple, fast, cross-platform, and object-oriented multimedia API
description : |
    SFML provides a simple interface to the various components of your PC, to ease the development of games and multimedia applications. It is composed of five modules: system, window, graphics, audio and network.
builddeps   :
    - pkgconfig(flac)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(vorbisenc)
    - pkgconfig(x11)
    - pkgconfig(xcb-image)
    - pkgconfig(xrandr)
    - libjpeg-turbo-devel
setup      : |
    %cmake -DSFML_INSTALL_PKGCONFIG_FILES=1 -DSFML_BUILD_EXAMPLES=1
build      : |
    %make
install    : |
    %make_install
